name: inventarisapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0' # Sesuaikan dengan versi SDK minimum yang sesuai dengan project Anda

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  sign_in_button: ^3.2.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  image_picker: ^1.1.2
  animated_text_kit: ^4.2.2
  flutter_gradient_animation_text: ^1.0.2

  path_provider: ^2.1.5
  sqflite: ^2.4.1

  connectivity_plus: ^6.1.0
  http: ^1.2.2

  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment jika ada aset tambahan yang ingin ditambahkan
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment jika ingin menambahkan font custom
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
